name: GitHub Pages Deploy

on:
  push:
    branches:
      - fork/stable
      - fork/beta
      - fork/origin-stable-fast
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      # 宛先の指定
      - name: Setting stable
        if: ${{ github.ref == 'refs/heads/fork/stable' }}
        run: echo "destination=stable" >> "$GITHUB_ENV"
      - name: Setting beta
        if: ${{ github.ref == 'refs/heads/fork/beta' }}
        run: echo "destination=beta" >> "$GITHUB_ENV"
      - name: Setting origin-fast
        if: ${{ github.ref == 'refs/heads/fork/origin-stable-fast' }}
        run: echo "destination=origin-fast" >> "$GITHUB_ENV"

      - name: Deploy
        if: ${{ env.destination != '' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: ${{ env.destination }}
